修改说明文字，修改ipv6路由探测bug

diff --git a/luci-app-nat6-helper/root/etc/init.d/nat6-helper b/luci-app-nat6-helper/root/etc/init.d/nat6-helper
--- a/luci-app-nat6-helper/root/etc/init.d/nat6-helper
+++ b/luci-app-nat6-helper/root/etc/init.d/nat6-helper
@@ -13,12 +13,11 @@ EXTRA_HELP="set_lan:Setting ULA, IPv6-DNS and DHCPv6
 enable=$(uci get nat6-helper.@nat6-helper[0].enabled)                                     #插件是否启用
 WAN6_NAME=$(uci get nat6-helper.@nat6-helper[0].name)                                     #选定的IPv6上行接口，默认为wan6
 ULA_PREFIX=$(uci get network.globals.ula_prefix)                                          #IPv6 ULA
-PREFIX_LEN=$(echo $ULA_PREFIX | awk -F/ '{print $2}')                                     #提取设定的ULA的前缀长度
 
 interface=$(uci get "network.$WAN6_NAME.device" || uci get "network.$WAN6_NAME.ifname")   #获取选中的ipv6接口的物理接口
 last_if=$(ip6tables-save -t nat | grep "v6NAT" | awk '{print $4}' | head -n 1)            #获取之前设置的出口网口
 #gateway=$(ip -6 route | grep "default from 2" | awk '{print $5}')                        #获取当前状态默认IPv6网关
-gateway=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $WAN6_INTERFACE" | grep -i -o 'via.*' | cut -d ' ' -f 2 | head -n 1)   #获取网关的更好的写法，对应接口
+gateway=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $interface" | grep -i -o 'via.*' | cut -d ' ' -f 2 | head -n 1)   #获取网关的更好的写法，对应接口
 last_gw=$(ip -6 route | grep "2000::/3" | awk '{print $3}')                               #之前由脚本设置的IPv6路由的网关地址
 #网络变动后IPv6网关可能会变，以及用户有可能重新选择ipv6网口，所以需要先获取之前脚本设置的ipv6网关，用于组合出删除旧的路由的命令
 #原先的default via命令有可能会冲突，所以改用nat6脚本中的只路由到公网的ip，即2开头的ip
@@ -46,6 +45,8 @@ set_lan()
     uci set dhcp.lan.ra_default='1'                                                 #总是通告默认路由，关键 0-存在默认路由且具有全局IPv6地址 1-存在默认路由但没有全局IPv6地址 2-两者均不满足
  
     #配置LAN接口的IPv6分配长度
+    ULA_PREFIX=$(uci get network.globals.ula_prefix)                                #局域网LUA，LUA可能会被33行更新，故在此处重新获得
+    PREFIX_LEN=$(echo $ULA_PREFIX | awk -F/ '{print $2}')                           #提取设定的ULA的前缀长度，LUA可能会被33行更新，故在此处获得
     uci set network.lan.ip6assign="$PREFIX_LEN"                                     #设置LAN接口的IPv6分配长度，默认ULA时应为64
 
     #LAN接口强制DHCP
@@ -53,7 +54,7 @@ set_lan()
 
     #取消禁止解析IPv6 DNS记录
     uci delete dhcp.@dnsmasq[0].filter_aaaa                                         #删除dnsmasq DHCPv6服务器的AAAA记录过滤器
-    
+
     #要求openwrt中打开防火墙，基本设置和区域中，打开转发。但是，基本设置其实
     #是default，实测不改动也是可以的；并且安全起见最好不要改变“WAN”区域中转发的配置。
     #uci set firewall.@defaults[0].forward='ACCEPT'                                  #基本设置中设置允许转发，即没有指定防火墙区域等情况时，默认允许转发
@@ -90,7 +91,7 @@ start_nat6()
         fi
         COUNT=$((COUNT+1))
         sleep $COUNT
-        PROBE=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $WAN6_INTERFACE" | grep -i -o 'via.*' | wc -l)   #探测是否具有带网关的默认IPv6路由
+        PROBE=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $interface" | grep -i -o 'via.*' | wc -l)   #探测是否具有带网关的默认IPv6路由
     done
 
     #开始设置nat6
@@ -103,7 +104,7 @@ start_nat6()
 
     #检测IPv6上行接口默认路由网关是否存在，如果默认路由网关不存在，则会写入错误日志并退出脚本
     if [ -z "$gateway" ] ; then
-            logger -t nat6-helper "Fatal error: No IPv6 gateway for $WAN6_INTERFACE found" && exit 1
+            logger -t nat6-helper "Fatal error: No IPv6 gateway for $interface found" && exit 1
     fi
 
     #检测当前ULA是否符合RFC4193定义的ULA前缀范围fc00::/7(增加dc00::/7)
