修改bug

diff --git a/luci-app-nat6-helper/root/etc/init.d/nat6-helper b/luci-app-nat6-helper/root/etc/init.d/nat6-helper
--- a/luci-app-nat6-helper/root/etc/init.d/nat6-helper
+++ b/luci-app-nat6-helper/root/etc/init.d/nat6-helper
@@ -10,16 +10,21 @@ EXTRA_HELP="set_lan:Setting ULA, IPv6-DNS and DHCPv6
             reset_lan:Resetting ULA, IPv6-DNS and DHCPv6
             ipv6_daemon:ipv6-Daemon"
 
-enable=$(uci get nat6-helper.@nat6-helper[0].enabled)                                    #插件是否启用
-WAN6_NAME=$(uci get nat6-helper.@nat6-helper[0].name)                                    #选定的IPv6上行接口，默认为wan6
-ULA_PREFIX=$(uci get network.globals.ula_prefix)                                         #IPv6 ULA
-PREFIX_LEN=$(echo $ULA_PREFIX | awk -F/ '{print $2}')                                    #提取设定的ULA的前缀长度
+enable=$(uci get nat6-helper.@nat6-helper[0].enabled)                                     #插件是否启用
+WAN6_NAME=$(uci get nat6-helper.@nat6-helper[0].name)                                     #选定的IPv6上行接口，默认为wan6
+ULA_PREFIX=$(uci get network.globals.ula_prefix)                                          #IPv6 ULA
+PREFIX_LEN=$(echo $ULA_PREFIX | awk -F/ '{print $2}')                                     #提取设定的ULA的前缀长度
 
-interface=$(uci get "network.$WAN6_NAME.device" || uci get "network.$WAN6_NAME.ifname")  #获取选中的ipv6接口的物理接口
-last_if=$(ip6tables-save -t nat | grep "v6NAT" | awk '{print $4}' | head -n 1)                       #获取之前设置的出口网口
+keepipv6_enabled=$(uci get nat6-helper.@check_ipv6[0].keepipv6_enabled)                   #ipv6守护是否启用
+daemon_running=$(uci get nat6-helper.@check_ipv6[0].daemon_running)                       #ipv6守护运行状态
+ping_host=$(uci get nat6-helper.@check_ipv6[0].ping_host)                                 #ping主机
+ping_period=$(uci get nat6-helper.@check_ipv6[0].ping_period)                             #ping周期
+
+interface=$(uci get "network.$WAN6_NAME.device" || uci get "network.$WAN6_NAME.ifname")   #获取选中的ipv6接口的物理接口
+last_if=$(ip6tables-save -t nat | grep "v6NAT" | awk '{print $4}' | head -n 1)            #获取之前设置的出口网口
 #gateway=$(ip -6 route | grep "default from 2" | awk '{print $5}')                        #获取当前状态默认IPv6网关
-gateway=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $WAN6_INTERFACE" | grep -i -o 'via.*' | cut -d ' ' -f 2 | head -n 1)   #获取网关的更好的写法
-last_gw=$(ip -6 route | grep "2000::/3" | awk '{print $3}')                              #之前由脚本设置的IPv6路由的网关地址
+gateway=$(ip -6 route | grep -i '^default.*via' | grep -i -F "dev $WAN6_INTERFACE" | grep -i -o 'via.*' | cut -d ' ' -f 2 | head -n 1)   #获取网关的更好的写法，对应接口
+last_gw=$(ip -6 route | grep "2000::/3" | awk '{print $3}')                               #之前由脚本设置的IPv6路由的网关地址
 #网络变动后IPv6网关可能会变，以及用户有可能重新选择ipv6网口，所以需要先获取之前脚本设置的ipv6网关，用于组合出删除旧的路由的命令
 #原先的default via命令有可能会冲突，所以改用nat6脚本中的只路由到公网的ip，即2开头的ip
 
@@ -86,7 +91,7 @@ start_nat6()
     do
         if [ $COUNT -gt $MAX_TRIES ]
         then
-            logger -t nat6-helper "Fatal error: No IPv6 route found (reached retry limit)" && exit 1   #多次尝试后无法获得带网关的默认IPv6路由，失败退出
+            logger -t nat6-helper "Fatal error: No default IPv6 route found (reached retry limit)" && exit 1   #多次尝试后无法获得带网关的默认IPv6路由，失败退出
         fi
         COUNT=$((COUNT+1))
         sleep $COUNT
@@ -111,9 +116,11 @@ start_nat6()
         logger -t nat6-helper "Fatal error: IPv6 ULA prefix $ULA_PREFIX seems invalid. Please verify that a prefix is set and valid." && exit 1
     fi
 
-    #设置nat6并添加标识 Add IPv6 NAT rule to /etc/firewall.user
+    #设置nat6并添加标识 ##Add IPv6 NAT rule to /etc/firewall.user
     ip6tables -t nat -I POSTROUTING -o $interface -m comment --comment "v6NAT" -j MASQUERADE > /dev/null 2>&1                  #-A最后 -I最前，优先匹配
-    #echo "ip6tables -t nat -I POSTROUTING -o $interface -m comment --comment \"v6NAT\" -j MASQUERADE" >> /etc/firewall.user   #将路由规则添加到/etc/firewall.user
+    if ! grep -q "ip6tables -t nat -I POSTROUTING -o $interface -m comment --comment \"v6NAT\" -j MASQUERADE" /etc/firewall.user; then
+        echo "ip6tables -t nat -I POSTROUTING -o $interface -m comment --comment \"v6NAT\" -j MASQUERADE" >> /etc/firewall.user
+    fi
 
     #检查上一条命令执行的结果，如果返回值为0，则说明命令执行成功，输出一条日志记录添加IPv6 masquerading规则到
     #防火墙的情况，否则执行失败，输出一条日志记录添加IPv6 masquerading规则失败的情况，并且终止脚本的执行。
@@ -161,15 +168,12 @@ stop_nat6()
     #删除之前在路由表为目的地为IPv6公网的流量设置的路由规则。接口关闭或者清除配置时调用，故不需要校验插件是否启用。
     ip -6 route del "2000::/3" via $last_gw dev $last_if  > /dev/null 2>&1
     
-
+    #删除nat6设置
     while ip6tables -t nat -C POSTROUTING -o $last_if -m comment --comment v6NAT -j MASQUERADE >/dev/null 2>&1; do
         ip6tables -t nat -D POSTROUTING -o $last_if -m comment --comment v6NAT -j MASQUERADE >/dev/null 2>&1
     done
+    sed -i "/ip6tables -t nat -I POSTROUTING -o $last_if -m comment --comment \"v6NAT\" -j MASQUERADE/d" /etc/firewall.user > /dev/null 2>&1   #删除/etc/firewall.user中路由规则
 
-
-    #删除nat6设置
-    ip6tables -t nat -D POSTROUTING -o $last_if -m comment --comment v6NAT -j MASQUERADE > /dev/null 2>&1
-    #sed -i "/ip6tables -t nat -A POSTROUTING -o $last_if -m comment --comment \"v6NAT\" -j MASQUERADE/d" /etc/firewall.user > /dev/null 2>&1   #删除/etc/firewall.user中路由规则
 
     #向系统日志输出清除设置成功信息
     if !(ip -6 route | grep -q "2000::/3") && !(ip6tables-save -t nat | grep -q "v6NAT");then
@@ -182,7 +186,7 @@ reset_lan()
     #插件未关闭则退出
     [ $enable = "1" ] && { logger -t nat6-helper "Please disable the nat6-helper plugin before one-key configuration."; exit 0; }
     
-    stopNat6
+    stop_nat6
 
     #重设DHCPv6和IPv6-DNS，LUA为初始的或者d00:6666:6666::/64，不需要恢复
     uci set network.$WAN6_NAME.dns=''                                               #清空DNS
@@ -221,6 +225,9 @@ reset_lan()
 
 ipv6_daemon()
 {
+    #守护未开启则退出
+    [ $keepipv6_enabled = "0" ] && exit 0
+
     # 已有运行则退出
     ["$daemon_running" = "1"] && exit 0
     
@@ -228,26 +235,25 @@ ipv6_daemon()
     uci set nat6-helper.@check_ipv6[0].daemon_running=1
     uci commit nat6-helper
 
-    keepipv6_enabled=$(uci get nat6-helper.@check_ipv6[0].keepipv6_enabled)
-    daemon_running=$(uci get nat6-helper.@check_ipv6[0].daemon_running)
-    wan6_name=$(uci get nat6-helper.@nat6-helper[0].name)
-    ping_host=$(uci get nat6-helper.@check_ipv6[0].ping_host)
-    ping_period=$(uci get nat6-helper.@check_ipv6[0].ping_period)
-
     while true; do
         # 判断守护是否启用
         if [ "$keepipv6_enabled" = "1" ]; then
             
             # running被关闭按钮强制设置为0，则退出,相当于锁被没收
-            ["$daemon_running" = "0"] && exit 0
-            
+            if ["$daemon_running" = "0"]; then
+                # 设置为结束运行,相当于解锁
+                uci set nat6-helper.@check_ipv6[0].daemon_running=0
+                uci commit nat6-helper
+                exit 0
+            fi
+
             # Ping检测
-            ping6 -c 3 -I "$wan6_name" "$ping_host" >/dev/null 2>&1
-            if [ "$ret" -ne "0" ]; then
-                logger -t nat6-helper "The IPv6 network connectivity on interface $interface is abnormal, and the interface is being restarted"
-                ifdown $wan6_name && ifup $wan6_name >/dev/null 2>&1
-            else
+            ping6 -c 3 -I "$WAN6_NAME" "$ping_host" >/dev/null 2>&1
+            if [ $? -eq 0 ]; then
                 logger -t nat6-helper "The IPv6 network connectivity on interface $interface is normal"
+            else
+                logger -t nat6-helper "The IPv6 network connectivity on interface $interface is abnormal, and the interface is being restarted"
+                ifdown $WAN6_NAME && ifup $WAN6_NAME >/dev/null 2>&1
             fi
 
             # 等待指定时间后再次检测
@@ -256,7 +262,7 @@ ipv6_daemon()
             # 设置为结束运行,相当于解锁
             uci set nat6-helper.@check_ipv6[0].daemon_running=0
             uci commit nat6-helper
-            break
+            exit 0
         fi
     done
 }
